### ISSUE TITLE
How to launch intent from library module

### ISSUE THREAD

**Issue by alorma** [airbnb/Showkase#116]
I have a library module where I've added Showkase as a `compileOnly` dependency, to allow who implements the module decide if want te add the module or not.

When I try to add the method to create the intent, is not created.

Method will be there:

https://github.com/alorma/Compose-Debug-Drawer/blob/main/developer-shortcuts/src/main/java/com/alorma/developer_shortcuts/ShortcutsModule.kt#L20

And this is the gradle:

https://github.com/alorma/Compose-Debug-Drawer/blob/main/developer-shortcuts/build.gradle#L52

Thanks

**Comment by vinaygaba** [comment]
Thanks for reporting! I'll have to pull the code and play with it to debug it. Will get back once I have more info @alorma !

**Comment by alorma** [comment]
Many appreciated.

Repository is ready to clone and use, you won't need any special config for it.

Thanks

**Comment by vinaygaba** [comment]
Hey! I was able to run Showkase in Compose-Debug-Drawer. I'm curious about the use case you are trying to support? Showkase requires the presence of a `@ShowkaseRoot`. If you look at the README, you will see one of the installation steps requires you to add the root module. 

```kotlin
@ShowkaseRoot
class MyRootModule: ShowkaseRootModule
```

Once I added that to the developer-shortcuts module, I was able to run it correctly (I downgraded compose to `alpha05` because that's the version of compose that Showkase uses and `alpha06` seems to be incompatible. Although I'll upgrade over the weekend).

I'm guessing that you don't want your library to add the `ShowkaseRootModule`? Would love to know more about how you imagined it @alorma

**Comment by alorma** [comment]
Hi @vinaygaba thanks for your time and your answer.

I Was try to create a default "shortcuts" module for common tools uses on android apps / compose apps, I've added leak canary, notification channels... and I thought your library could be a great addition to it.

It still can be done, but not from a library itself, so users will need to do it by themselves.+
Many thanks
