### ISSUE TITLE
How to omit preview composables from showkase

### ISSUE THREAD

**Issue by vyshas** [airbnb/Showkase#158]
Excellent library so far and very useful. Is there a way to omit Preview components from not appearing in Showkase browser ?

**Comment by vinaygaba** [comment]
Glad to hear that you like it. I think this is a pretty valid request. I'm curious to learn more about your use case. Why do you want something to be previewed in Android Studio but want to avoid it in the Showkase browser? Just trying to learn more about how this library is being used @vyshas

**Comment by vyshas** [comment]
Hi @vinaygaba , 

Showkase actually solved a big problem for our android team  as it would provide out of the box solution for design catalog or UI components app built in compose from our UI components library. We have plenty of engineers working on the UI components library and AS preview is used for debugging, seeing how the components appears in AS however not all of them need to be there in showkase browser as we use the browser as as UI components catalog app for designers, PMs, engineers, etc.... 

There are  composable items that is part of another composable and that needs to be previewed for development but not in showkase browser.

**Comment by L7ColWinters** [comment]
Hi, I wanted to chime in and say that liking what you have provided with Showkase so far. We have a bug where if we want a screen that has a vertical scroll, it will crash showkase. If we could omit those previews for the full screens then it would be easier to use Showkase. I know that ideally you would just fix the bug but since many bugs can show up over time, until those bugs get fixed it would be nice just to turn things off. Also like vyshas above it's nice to control which composables you want to show.

**Comment by vinaygaba** [comment]
Thank you for providing more context. I'm working on an API that would allow you to skip the composables! Will add y'all to the PR once its ready (should be soon)

**Comment by vinaygaba** [comment]
PR is up for supporting this.
