### ISSUE TITLE
implementation or debugImplementation

### ISSUE THREAD

**Issue by StylianosGakis** [airbnb/Showkase#189]
This is more of a question instead of an issue.

In the sample project and in the setup section, it is recommended to use `implementation` instead of `debugImplementation`. Now this tool just like something like leakCanary feels like is something that would only be used in the non-production versions of the app.

So I have two questions.
* Is there a specific reason that the suggestion isn't `debugImplementation` or there is at least a note about it? 
* If we do just add it to the production dependencies too, does it simply not matter because `minifyEnabled = true` gets rid of any trace of Showkase and therefore it's completely fine to add it to the production build type too?

**Comment by vinaygaba** [comment]
This is on me - I need to update the documentation. You are right, you should be using `debugImplementation` instead (I do as well!). In addition, you should also declare your `@ShowkaseRoot` implementation in the debug sourceSet. One last thing you will need to do with this setup is to take an additional `implementation` dependency on `com.airbnb.android:showkase-annotation` to ensure that you can use the Showakse annotations in the rest of your codebase, otherwise you will see errors (since you took a `debugImplementation` on the main showakse dependency). This is completely reasonable to do as the `showkase-annotation` dependency merely brings in ~7 annotations that it needs.

**Comment by vinaygaba** [comment]
^This setup will ensure that there is no way in which there can be any apk size impact on your release builds. I'll be updating the documentation to reflect this soon!

**Comment by StylianosGakis** [comment]
Awesome, that's very good to know!
